[package]
name = "gerb"
version = "0.0.0"
edition = "2021"
authors = ["Manos Pitsidianakis <epilys@nessuent.xyz>"]
description = "font editor"
license-file = "LICENSE"
readme = "README.md"
homepage = "https://github.com/epilys/gerb"
repository = "https://github.com/epilys/gerb"

[dependencies]
chrono = "0.4"
futures = "0.3"
futures-util = "0.3"
generational-arena = "0.2"
glib = { version = "^0.15" }
gtk = { version = "^0.15", features = [ "v3_20" ] }
image = { version = "0.24", default-features = false, features = ["png"], optional = true }
indexmap = { version = "1.9" }
nalgebra = "0.32.1"
notify-rust = { version = "4", optional = true, features = ["images"] }
once_cell = "1.2.0"
plist = { version = "1" }
quick-xml = { version = "0.21", features = [ "serialize" ] }
rand = { version = "0.8" }
serde = { version = "1.0", features = [ "derive" ] }
serde_json = { version = "1" }
toml_edit = { version = "0.17.1", features = ["serde", "easy", "perf"] }
xdg = { version = "2.1" }

[dependencies.cairo-rs]
version = "^0.15"
optional = true
features = ["svg", ]

[dependencies.pyo3]
version = "0.18"
optional = true
features = ["auto-initialize"]

[dependencies.uuid]
version = "1.2.1"
features = [
    "v4",                # Lets you generate random UUIDs
    "fast-rng",          # Use a faster (but still sufficiently random) RNG
    "macro-diagnostics", # Enable better diagnostics for compile-time UUIDs
]

[features]
default = ["svg", "python"]
svg = ["cairo-rs/svg", ]
python = ["pyo3", ]
notifications = ["notify-rust", "image"]

[profile.release]
lto = "fat"
codegen-units = 1
opt-level = "s"
debug = false
strip = true
